M48
; DRILL file {KiCad (6.0.5)} date Fri Jun  3 01:41:33 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-03T01:41:33-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X92.71Y-76.835
X92.71Y-116.84
X242.824Y-76.835
X242.824Y-116.84
T0
M30
