M48
; DRILL file {KiCad (6.0.5)} date Thu May  5 00:21:01 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-05T00:21:01-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.700
%
G90
G05
T1
X178.817Y-86.9
X202.117Y-86.9
T2
X97.167Y-64.985
X97.167Y-76.415
T3
X81.128Y-117.119
X81.428Y-66.319
X208.128Y-66.319
X208.128Y-117.119
T0
M30
