M48
; DRILL file {KiCad (6.0.4)} date Thu Apr 21 23:03:11 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-21T23:03:11-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X104.93Y-63.27
X104.93Y-121.27
X153.93Y-63.27
X153.93Y-121.27
T2
X104.0Y-54.0
X104.0Y-130.0
X155.0Y-54.0
X155.0Y-130.0
T0
M30
