M48
; DRILL file {KiCad (6.0.4)} date Thu Apr  7 22:37:14 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-07T22:37:14-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X103.13Y-62.83
X103.13Y-120.83
X152.13Y-62.83
X152.13Y-120.83
T2
X104.0Y-54.0
X104.0Y-130.0
X155.0Y-54.0
X155.0Y-130.0
T0
M30
