M48
; DRILL file {KiCad (6.0.5)} date Fri Jun  3 00:54:06 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-03T00:54:06-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.700
%
G90
G05
T1
X72.731Y-91.44
X72.731Y-142.24
X123.531Y-91.44
X123.531Y-142.24
T0
M30
