M48
; DRILL file {KiCad (6.0.7)} date Wed Aug 24 09:29:10 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-24T09:29:10-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X7.4413Y-3.8403
X8.3587Y-3.8403
T2
X5.6857Y-2.3714
X5.6857Y-5.3635
X9.1896Y-2.3714
X9.1896Y-5.3635
T0
M30
