M48
; DRILL file {KiCad (6.0.5)} date Thu Jun  2 01:06:28 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-02T01:06:28-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.700
%
G90
G05
T1
X79.591Y-80.568
X91.021Y-80.568
T2
X72.731Y-91.44
X72.731Y-142.24
X123.531Y-91.44
X123.531Y-142.24
T0
M30
