M48
; DRILL file {KiCad (6.0.2)} date Tue Mar  8 14:05:25 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-08T14:05:25-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1457
%
G90
G05
T1
X3.1335Y-3.342
X3.5835Y-3.342
T2
X2.8634Y-3.6
X2.8634Y-5.6
X4.8634Y-3.6
X4.8634Y-5.6
T0
M30
