M48
; DRILL file {KiCad (6.0.7)} date Wed Aug 24 09:37:21 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-24T09:37:21-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1457
%
G90
G05
T1
X3.1335Y-3.342
X3.5835Y-3.342
T2
X2.8634Y-3.6
X2.8634Y-5.6
X4.8634Y-3.6
X4.8634Y-5.6
T0
M30
