M48
; DRILL file {KiCad 9.0.7} date 2026-02-20T16:36:17-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-20T16:36:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1457
%
G90
G05
T1
X6.3406Y-2.198
X6.3406Y-2.648
T2
X6.6Y-1.6
X6.6Y-4.6
X9.6Y-1.6
X9.6Y-4.6
M30
