M48
; DRILL file {KiCad 9.0.7} date 2026-03-07T09:56:33-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-07T09:56:33-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1299
%
G90
G05
T1
X-3.1243Y0.3255
X-3.1243Y0.2455
X-2.9243Y0.2855
T2
X-5.229Y0.8339
X-5.229Y0.3839
M30
