M48
; DRILL file {KiCad (6.0.5)} date Fri Jun  3 01:10:52 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-03T01:10:52-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.700
%
G90
G05
T1
X167.64Y-40.64
X167.64Y-116.84
X243.84Y-40.64
X243.84Y-116.84
T0
M30
